name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "install dfx"
      run: |
       wget https://sdk.dfinity.org/install.sh
       echo DFX_VERSION=0.7.0
       yes Y | DFX_VERSION=0.7.0 sh install.sh
       echo "/home/runner/bin" >> $GITHUB_PATH
    - name: "dfx cache install"
      run: dfx cache install
    - name: "install vessel"
      run: wget --output-document /home/runner/bin/vessel https://github.com/dfinity/vessel/releases/download/v0.6.1/vessel-linux64 && chmod +x /home/runner/bin/vessel
    - name: "install candid tool"
      run: wget --output-document /home/runner/bin/candiff https://github.com/dfinity/candid/releases/download/2020-08-18/candiff-linux64 && chmod +x /home/runner/bin/candiff
    - name: "candiff help (sanity check)"
      run: candiff --help
    - name: "install didc tool"
      run: wget --output-document /home/runner/bin/didc https://github.com/dfinity/candid/releases/download/2020-08-18/didc-linux64 && chmod +x /home/runner/bin/didc
    - name: "didc help (sanity check)"
      run: didc --help
    - name: "install libsdl2, for ic-mt"
      run: sudo apt-get install libsdl2-dev
    - name: "install ic-mt tool"
      run: wget --output-document /home/runner/bin/ic-mt https://github.com/matthewhammer/ic-game-terminal/releases/download/2020-12-15-G/ic-mt-linux64 && chmod +x /home/runner/bin/ic-mt
    - name: "ic-mt help (sanity check)"
      run: ic-mt --help
    - name: "test"
      run: ./scripts/MirrorGarden-test-headless.sh
    - name: "docs"
      run: /home/runner/.cache/dfinity/versions/0.6.18/mo-doc
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/