name: "build"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment variables to set for dfx
    env:
      DFX_VERSION: 0.7.0
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        echo y | DFX_VERSION=$DFX_VERSION bash -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
        echo "/home/runner/bin" >> $GITHUB_PATH
        ./scripts/vessel-install.sh
        ./scripts/repl-install.sh

    - name: Build
      run: |
        dfx cache install
        # cp -f $HOME/bin/moc $HOME/.cache/dfinity/versions/$DFX_VERSION/moc
        dfx start --background
        dfx deploy --no-wallet MirrorGarden
    - name: "install libsdl2, for ic-mt"
      run: sudo apt-get install libsdl2-dev
    - name: "install ic-mt tool"
      run: wget --output-document /home/runner/bin/ic-mt https://github.com/matthewhammer/ic-game-terminal/releases/download/2020-12-15-G/ic-mt-linux64 && chmod +x /home/runner/bin/ic-mt
    - name: "ic-mt help (sanity check)"
      run: ic-mt --help
    - name: "test"
      run: ./scripts/MirrorGarden-test-headless.sh
    - name: "docs"
      run: /home/runner/.cache/dfinity/versions/0.7.0/mo-doc
    - name: Upload docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/